---
on: push
name: Docker build and run
permissions:
  contents: read
jobs:
  build:
    name: Docker build and run
    if: '!github.event.deleted'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Docker build
        run: docker build --tag github-security-jira:latest .
      - name: Run in Docker
        run: docker run -t --rm github-security-jira:latest --version
